<?php /**   */ ?>
<?php
$optionsHelper = $this->helper('TemplateMonster\ThemeOptions\Helper\Data');
?>

<?php if($optionsHelper->getLogoType() == 'text'): ?>
    /** Logo **/
    <?php $sloganPosition = $optionsHelper->getSloganPosition(); ?>
    <?php $direction = 'row' ?>
    <?php if($sloganPosition == 'top'): $direction = 'column-reverse';  ?>
    <?php elseif($sloganPosition == 'bottom'): $direction = 'column';  ?>
    <?php elseif($sloganPosition == 'left'): $direction = 'row-reverse'; endif; ?>
    <?php
        $logoFontSize = $optionsHelper->getLogoFontSize();
        $logoLineHeight = $optionsHelper->getLogoLineHeight();
        $logoTextColor = $optionsHelper->getLogoTextColor();
        $sloganFontSize = $optionsHelper->getSloganFontSize();
        $sloganLineHeight = $optionsHelper->getSloganLineHeight();
        $sloganTextColor = $optionsHelper->getSloganTextColor();
    ?>
    .tm-logo-container {
        display: inline-block;
    }
    .tm-logo-text {
        display:flex;
        flex-direction: <?php echo $direction; ?>;
        flex-wrap: nowrap;
        width: auto;
    }
    .tm-logo-text a.logo {
        text-decoration: none
    }
    .tm-logo-text .logo{
        max-width: 100%;
        <?php echo $logoFontSize ? 'font-size: ' . $logoFontSize . 'px;' : '' ?>
        <?php echo $logoLineHeight ? 'line-height: ' . $logoLineHeight . 'px;' : '' ?>
        <?php echo $logoTextColor ? 'color: ' . $logoTextColor . ';' : '' ?>
    }
    .tm-logo-text .tm-slogan {
        max-width: 100%;
        <?php echo $sloganFontSize ? 'font-size: ' . $sloganFontSize . 'px;' : '' ?>
        <?php echo $sloganLineHeight ? 'line-height: ' . $sloganLineHeight . 'px;' : '' ?>
        <?php echo $sloganTextColor ? 'color: ' . $sloganTextColor . ';' : '' ?>
    }
    /** end Logo **/
<?php endif; ?>

<?php if($optionsHelper->getColorSchemeStatus()): ?>

/** Primary Color **/

/* put this selectors for primary color/background */
.actions-primary .action, .action.primary,
.checkout.methods .action.primary {
    <?php if ($optionsHelper->getPrimaryColor()): ?>
        background-color: <?php echo $optionsHelper->getPrimaryColor(); ?>;
    <?php endif; ?>
}
a {
    <?php if ($optionsHelper->getPrimaryColor()): ?>
        color: <?php echo $optionsHelper->getPrimaryColor(); ?>;
    <?php endif; ?>
}
/**/

/** Secondary Color **/

/* put this selectors for secondary color/background */
.filter-options-title {
    <?php if ($optionsHelper->getSecondaryColor()): ?>
        color: <?php echo $optionsHelper->getSecondaryColor(); ?>;
    <?php endif; ?>
}
/**/

body {
    <?php if ($optionsHelper->getBodyBackgroundColor()): ?>
        background-color: <?php echo $optionsHelper->getBodyBackgroundColor(); ?>;
    <?php endif; ?>
    <?php if ($optionsHelper->isBodyBackgroundImage()) : ?>
        background-image: <?php echo $optionsHelper->getBodyBackgroundImage() ? 'url(' . $this->getBaseUrl() . 'pub/media/theme_options/' . $optionsHelper->getBodyBackgroundImage() . ')' : 'none' ?>;
        background-size: <?php echo $optionsHelper->getBodyBackgroundImageSize(); ?>;
        background-attachment: <?php echo $optionsHelper->getBodyBackgroundImageAttachment(); ?>;
        background-position: <?php echo $optionsHelper->getBodyBackgroundImagePosition(); ?>;
        background-repeat: <?php echo $optionsHelper->getBodyBackgroundImageRepeat(); ?>;
    <?php endif; ?>
}

header.page-header,
.rd-navbar-static {
    <?php if ($optionsHelper->getHeaderBackgroundColor()): ?>
        background-color: <?php echo $optionsHelper->getHeaderBackgroundColor(); ?>;
    <?php endif; ?>
    <?php if ($optionsHelper->isHeaderBackgroundImage()) : ?>
        background-image: <?php echo $optionsHelper->getHeaderBackgroundImage() ? 'url(' . $this->getBaseUrl() . 'pub/media/theme_options/' . $optionsHelper->getHeaderBackgroundImage() . ')' : 'none' ?>;
        background-size: <?php echo $optionsHelper->getHeaderBackgroundImageSize(); ?>;
        background-attachment: <?php echo $optionsHelper->getHeaderBackgroundImageAttachment(); ?>;
        background-position: <?php echo $optionsHelper->getHeaderBackgroundImagePosition(); ?>;
        background-repeat: <?php echo $optionsHelper->getHeaderBackgroundImageRepeat(); ?>;
    <?php endif; ?>
}

.page-footer{
    <?php if ($optionsHelper->getFooterBackgroundColor()): ?>
        background-color: <?php echo $optionsHelper->getFooterBackgroundColor(); ?>;
    <?php endif; ?>
    <?php if ($optionsHelper->isFooterBackgroundImage()) : ?>
        background-image: <?php echo $optionsHelper->getFooterBackgroundImage() ? 'url(' . $this->getBaseUrl() . 'pub/media/theme_options/' . $optionsHelper->getFooterBackgroundImage() . ')' : 'none' ?>;
        background-size: <?php echo $optionsHelper->getFooterBackgroundImageSize(); ?>;
        background-attachment: <?php echo $optionsHelper->getFooterBackgroundImageAttachment(); ?>;
        background-position: <?php echo $optionsHelper->getFooterBackgroundImagePosition(); ?>;
        background-repeat: <?php echo $optionsHelper->getFooterBackgroundImageRepeat(); ?>;
    <?php endif; ?>
}
<?php endif; ?>

/** Typography Settings  **/

/*Primary font family*/
body {
    <?php if ($optionsHelper->getPrimaryFontFamily()): ?>
        font-family: <?php echo $optionsHelper->getPrimaryFontFamily(); ?>;
    <?php endif; ?>
    <?php if ($optionsHelper->getPrimaryFontSize()): ?>
        font-size: <?php echo $optionsHelper->getPrimaryFontSize(); ?>;
    <?php endif; ?>
    <?php if ($optionsHelper->getPrimaryLineHeight()): ?>
        line-height: <?php echo $optionsHelper->getPrimaryLineHeight(); ?>;
    <?php endif; ?>

    <?php if ($optionsHelper->getPrimaryFontColor()): ?>
        color: <?php echo $optionsHelper->getPrimaryFontColor(); ?>;
    <?php endif; ?>
}
a {
    <?php if ($optionsHelper->getPrimaryLinkColor()): ?>
        color: <?php echo $optionsHelper->getPrimaryLinkColor(); ?>;
    <?php endif; ?>
}

/*Secondary font family*/
<?php if ($optionsHelper->getSecondaryFontFamily()): ?>
    .block-title,
    .page-title,
    .section-title,
    .sm-desktop nav.navigation li.level-top > a,
    .navigation a.level-top .tm-megamenu ul.level1 > li > a,
    .catalog-image-grid .category-grid .grid-inner_content > .category-link,
    .cms-index-index .banner-1_txt span,
    .cms-index-index .banner-1_txt a,
    .cms-index-index .banner-2_box-1 span,
    .cms-index-index .banner-2_box-2 span,
    .products-grid .product-item .product-item-name a,
    .products-list .product-item .product-item-name a,
    .column.main .block.newsletter .control .actions button.action.primary,
    .cms-index-index .add-info .add-info_txt h4,
    .page-footer h4{
        font-family: <?php echo $optionsHelper->getSecondaryFontFamily(); ?>;
    }
<?php endif; ?>
/* Category page */
<?php if ($columns = $optionsHelper->getProductItemWidth()): ?>
@media screen and (min-width: 1024px) {
    .grid-main .products-grid .product-item{
        -webkit-flex-basis: <?php echo $columns; ?>;
        -ms-flex-preferred-size: <?php echo $columns; ?>;
        flex-basis: <?php echo $columns; ?>;
        max-width: <?php echo $columns; ?>;
    }
}
<?php endif; ?>
/* END Category page */

@media (min-width: 768px) {
    ul.social-links {
        float: left;
        clear: both;
        width: 100%;
        padding: 0!important;
        text-align: left;
        list-style: none;
    }
    ul.social-links li {
        display: inline-block;
    }
}
@media (max-width: 768px) {
    ul.social-links {
        display: none;
    }
}

