<?php /**  */ ?>
<?php
$optionsHelper = $this->helper('TemplateMonster\ThemeOptions\Helper\Data');
?>
<style>

    #page-preloader{
        background-color: <?php echo $optionsHelper->getBodyBackgroundColor() ?: '#ffffff' ?>;
        <?php if ($optionsHelper->isBodyBackgroundImage()) : ?>
            background-image: <?php echo $optionsHelper->getBodyBackgroundImage() ? 'url(' . $this->getBaseUrl() . 'pub/media/theme_options/' . $optionsHelper->getBodyBackgroundImage() . ')' : 'none' ?>;
            background-size: <?php echo $optionsHelper->getBodyBackgroundImageSize(); ?>;
            background-attachment: <?php echo $optionsHelper->getBodyBackgroundImageAttachment(); ?>;
            background-position: <?php echo $optionsHelper->getBodyBackgroundImagePosition(); ?>;
            background-repeat: <?php echo $optionsHelper->getBodyBackgroundImageRepeat(); ?>;
        <?php endif; ?>
    }  

    #page-preloader .spinner:before{
        background-color: <?php echo $optionsHelper->getPrimaryColor() ?: '#30a0dd' ?>;
    }
    #page-preloader .spinner:after{
        background-color: <?php echo $optionsHelper->getSecondaryColor() ?: '#3bb141' ?>;
    }

</style>
